@urlDev=http://localhost:3051/api/v1/auth

### register 
POST {{urlDev}}/register
Content-Type: application/json 

{
    "username": "ghost13",
    "email": "ghos13@gmail.com",
    "phone": "012345678",
    "password": "1234678"
}

### login 
POST {{urlDev}}/login
Content-Type: application/json 

{
    "email": "ghost3@gmail.com",
    "password": "1234678"
}



