@urlDev=http://localhost:3051/api/labs


### Create lab
POST {{urlDev}}/
Content-Type: application/json

{
     "title": "Programmatic Video Editing with FFmpeg",
        "description": "As a YouTuber, one of my biggest time sucks is video editing, so I recently wrote several video editing scripts with FFmpeg to increse my productivity. It is a popular command line tool that can convert, transform, and filter nearly any multimedia format (over 100+ codecs supported). In the following lesson, we’ll look at a collection of useful techniques for working with FFmpeg that you can use to build your own video editing utilities or apps.",
        "authorID": "640c83824c85ce0493226ce4",
        "imgUrl": "https://fireship.io/lessons/ffmpeg-useful-techniques/img/featured.webp",
        "videoUrl": "https://youtu.be/26Mayv5JPz0",
        "steps":[
            "Convert a File to a Different Format","Extract Audio from a Video File","Create a High-Quality Animated Gif","Add Subtitles to a Video","Using FFmpeg in Firebase Cloud Functions"
        ],
        "tags": ["linux"]
}
### Create lab
POST {{urlDev}}/
Content-Type: application/json

{
     "title": "Pocketbase Chat App",
        "description": "In the following tutorial we will build a chat app with Pocketbase and Svelte. Pocketbase is a backend (inspired by Firebase) structured as a single executable file. It provides a realtime DB based on SQLite and user authentication system that allows us to quickly prototype and deploy a chat app.",
        "authorID": "640c83824c85ce0493226ce4",
        "imgUrl": "https://fireship.io/lessons/pocketbase-chat-app/img/featured.webp",
        "videoUrl": "https://youtu.be/gUYBFDPZ5qk",
        "steps":[
            "Pocketbase Setup","Frontend App","Deploying Pocketbase to Linode"],
        "tags": ["pocketbase", "svelte"]
}

### Get all labs
GET {{urlDev}}/

### Get lab by id
GET {{urlDev}}/id/640f1ee827f03a9ccb0affda

### Get lab by slug
GET {{urlDev}}/slug/pocketbase-chat-app
###
// Update lab
PUT {{urlDev}}/640f1f2d27f03a9ccb0affeb
Content-Type: application/json

{
     "title": "React Supabase Full Course test test update",
     "tags": [
        "pocketbase",
      "svelte", 
      "test"
     ]
}

### Delete lab
DELETE {{urlDev}}/640f1f2d27f03a9ccb0affeb