@urlDev=http://localhost:3051/api

### user
GET {{urlDev}}/users



### courses
GET {{urlDev}}/courses

### user
GET {{urlDev}}/labs

### register 
POST {{urlDev}}/auth/register
Content-Type: application/json 

{
    "username": "ghost3",
    "email": "ghost3@gmail.com",
    "phone": "012345678",
    "password": "1234678"
}

### login 
POST {{urlDev}}/auth/login
Content-Type: application/json 

{
    "email": "ghost3@gmail.com",
    "password": "1234678"
}

### all users
GET {{urlDev}}/users

### get user by id
GET {{urlDev}}/users/64072da6bd3a4aaea6b60b16

### update user by id
PUT {{urlDev}}/users/64072da6bd3a4aaea6b60b16
Content-Type:  application/json 

{
    "username": "ghost updated 2",
    "city": "tg2",
    "phone": "0123456789 updated2"
}

### delete user by id
DELETE {{urlDev}}/users/64072da6bd3a4aaea6b60b16


