@urlDev=http://localhost:3051/api

### user
GET {{urlDev}}/users

### all users
GET {{urlDev}}/users

### get user by id
GET {{urlDev}}/users/64072da6bd3a4aaea6b60b16

### update user by id
PUT {{urlDev}}/users/64072da6bd3a4aaea6b60b16
Content-Type:  application/json 

{
    "username": "ghost updated 2",
    "city": "tg2",
    "phone": "0123456789 updated2"
}

### delete user by id
DELETE {{urlDev}}/users/64072da6bd3a4aaea6b60b16
